components:
    schemas:
        TenantServiceInviteMemberBody:
            properties:
                email:
                    type: string
                role:
                    title: owner, admin, member
                    type: string
            type: object
        TenantServiceProvisionUserBody:
            properties:
                email:
                    type: string
                role:
                    type: string
            type: object
        TenantServiceUpdateTenantBody:
            properties:
                tenant:
                    properties:
                        createdAt:
                            type: string
                        enabled:
                            type: boolean
                        name:
                            type: string
                    type: object
                updateMask:
                    type: string
            type: object
        TenantServiceUpdateTenantUserBody:
            properties:
                role:
                    type: string
            type: object
        protobufAny:
            additionalProperties: {}
            properties:
                '@type':
                    type: string
            type: object
        rpcStatus:
            properties:
                code:
                    format: int32
                    type: integer
                details:
                    items:
                        $ref: '#/components/schemas/protobufAny'
                    type: array
                message:
                    type: string
            type: object
        tenantCreateTenantRequest:
            properties:
                name:
                    type: string
            type: object
        tenantCreateTenantResponse:
            properties:
                tenant:
                    $ref: '#/components/schemas/tenantTenant'
            type: object
        tenantInviteMemberResponse:
            properties:
                code:
                    type: string
                link:
                    type: string
                status:
                    type: string
            type: object
        tenantListMyTenantsResponse:
            properties:
                tenants:
                    items:
                        $ref: '#/components/schemas/tenantTenant'
                    type: array
            type: object
        tenantListTenantUsersResponse:
            properties:
                users:
                    items:
                        $ref: '#/components/schemas/tenantTenantUser'
                    type: array
            type: object
        tenantListTenantsResponse:
            properties:
                tenants:
                    items:
                        $ref: '#/components/schemas/tenantTenant'
                    type: array
            type: object
        tenantListUserTenantsResponse:
            properties:
                tenants:
                    items:
                        $ref: '#/components/schemas/tenantTenant'
                    type: array
            type: object
        tenantProvisionUserResponse:
            properties:
                status:
                    type: string
            type: object
        tenantTenant:
            properties:
                createdAt:
                    type: string
                enabled:
                    type: boolean
                id:
                    type: string
                name:
                    type: string
            type: object
        tenantTenantUser:
            properties:
                email:
                    type: string
                role:
                    type: string
                userId:
                    type: string
            type: object
        tenantUpdateTenantResponse:
            properties:
                tenant:
                    $ref: '#/components/schemas/tenantTenant'
            type: object
        tenantUpdateTenantUserResponse:
            properties:
                user:
                    $ref: '#/components/schemas/tenantTenantUser'
            type: object
info:
    title: v0/tenant.proto
    version: version not set
openapi: 3.0.3
paths:
    /api/v0/me/tenants:
        get:
            operationId: TenantService_ListMyTenants
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            summary: Public Endpoints
            tags:
                - TenantService
    /api/v0/tenants:
        get:
            operationId: TenantService_ListTenants
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            summary: Internal Admin Endpoints
            tags:
                - TenantService
        post:
            operationId: TenantService_CreateTenant
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/tenantCreateTenantRequest'
                required: true
                x-originalParamName: body
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/tenants/{tenant.id}:
        patch:
            operationId: TenantService_UpdateTenant
            parameters:
                - in: path
                  name: tenant.id
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TenantServiceUpdateTenantBody'
                required: true
                x-originalParamName: body
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/tenants/{tenantId}:
        delete:
            operationId: TenantService_DeleteTenant
            parameters:
                - in: path
                  name: tenantId
                  required: true
                  schema:
                    type: string
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/tenants/{tenantId}/invites:
        post:
            operationId: TenantService_InviteMember
            parameters:
                - in: path
                  name: tenantId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TenantServiceInviteMemberBody'
                required: true
                x-originalParamName: body
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/tenants/{tenantId}/users:
        get:
            operationId: TenantService_ListTenantUsers
            parameters:
                - in: path
                  name: tenantId
                  required: true
                  schema:
                    type: string
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
        post:
            operationId: TenantService_ProvisionUser
            parameters:
                - in: path
                  name: tenantId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TenantServiceProvisionUserBody'
                required: true
                x-originalParamName: body
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/tenants/{tenantId}/users/{userId}:
        patch:
            operationId: TenantService_UpdateTenantUser
            parameters:
                - in: path
                  name: tenantId
                  required: true
                  schema:
                    type: string
                - in: path
                  name: userId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TenantServiceUpdateTenantUserBody'
                required: true
                x-originalParamName: body
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
    /api/v0/users/{userId}/tenants:
        get:
            operationId: TenantService_ListUserTenants
            parameters:
                - in: path
                  name: userId
                  required: true
                  schema:
                    type: string
            responses:
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/rpcStatus'
                    description: An unexpected error response.
            tags:
                - TenantService
tags:
    - name: TenantService
