apiVersion: v1
kind: ServiceAccount
metadata:
  name: fga-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fga-setup
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fga-setup
subjects:
- kind: ServiceAccount
  name: fga-setup
  namespace: default
roleRef:
  kind: Role
  name: fga-setup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fga-setup
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: fga-setup
      restartPolicy: OnFailure
      containers:
      - name: setup
        # Use the same image as tenant-service as it contains the CLI
        image: localhost:32000/tenant-service
        command: ["/usr/bin/tenant-service"]
        args:
        - "create-fga-model"
        - "--fga-api-url=http://openfga:8080"
        - "--fga-api-token=42"
        - "--store-k8s-configmap-resource=default/tenant-service-fga-config"
